### ISSUE TITLE
A better way to access query string params

### ISSUE THREAD

**Issue by thelinuxlich** [lpil/wisp#39]
Right now we can do it like this:

```rust
// param "foo" should not be empty
use params <- try(get_query(req))
use #(_, search_term) <- try(list.find(
  params,
  fn(x) { x.0 == "foo" && x.1 != "" },
))
```

Ideally we'd have something to enforce the existence of query params like:

```rust
use params <- wisp.require_query_params(req, list_of_param_names) // params : Map(name, value)

// when you just want the whole thing without enforcing anything
use params <- wisp.qs_to_map(req) // params: Map(name, value)
```

**Comment by lpil** [comment]
It gets a little trickier when you consider that query parameters can't be stored in a map- the ordering matters and keys can be duplicated.

If nothing else a `get_query(r: Request) -> List(#(String, String))` would be an improvement, but perhaps we can do better.

**Comment by thelinuxlich** [comment]
Doesn't frameworks take a stance about how to parse duplicate query parameters? Like some parse "key[]=foo" into key: ["foo"] ?

**Comment by lpil** [comment]
I've been exploring API designs this evening and I'm not making much progress.

```gleam
use params <- wisp.require_query_params(req, list_of_param_names) // params : Map(name, value)
```
Why is it that a list of parameter names is passed in here? You'd still need to `map.get` on the params, so each parameter name would be in the code twice.

```gleam
use #(_, search_term) <- try(list.find(
  params,
  fn(x) { x.0 == "foo" && x.1 != "" },
))
```
Here there's an extra requirement of ensuring the query parameter doesn't have an empty value, which we also wouldn't want. Empty values are often useful.

**Comment by thelinuxlich** [comment]
The first was just an example of how I use it, not to be added to wisp. Maybe we can reuse https://github.com/sporto/gleam_qs ?

**Comment by lpil** [comment]
If we used that custom type based API the programmer would need to add a `case` for each parameter, which seems annoying than using `list.key_find`.

**Comment by thelinuxlich** [comment]
so maybe just a `wisp.get_query_as_list(req)` ?

**Comment by thelinuxlich** [comment]
No, should be a method that actually parses the qs

**Comment by lpil** [comment]
That's what `request.get_query` does, aye

```gleam
pub fn get_query(request: Request(a)) -> Result(List(#(String, String)), Nil)
```

**Comment by thelinuxlich** [comment]
yeah, I was barely awake when I wrote that, what I mean is we need a method that parses the qs and take a stance on arrays

**Comment by lpil** [comment]
It does- it keeps them. You can filter the list to get all the values, which is more concise an API than the custom type based approach in that library which forces you to use a case expression every time.
